export const ENV_CONSTS = {
    APP_TITLE,
    VITE_APP_TITLE: import.meta.env.VITE_APP_TITLE,
    DEVELOP_TITLE,
    VITE_TEST_TITLE: import.meta.env.VITE_TEST_TITLE,
    TEST_TITLE,
    VITE_DEVELOP_TITLE: import.meta.env.VITE_DEVELOP_TITLE,
    PRODUCT_TITLE,
    VITE_PRODUCT_TITLE: import.meta.env.VITE_PRODUCT_TITLE,
    PUBLIC_PATH,
    VITE_PUBLIC_PATH: import.meta.env.VITE_PUBLIC_PATH,
    REST_ACTIVE,
    VITE_REST_ACTIVE: import.meta.env.VITE_REST_ACTIVE,
    dev: import.meta.env.DEV,
    test: import.meta.env.TEST,
    prod: import.meta.env.PROD,
    url: import.meta.env.BASE_URL,
    mode: import.meta.env.MODE,
};
